### ISSUE TITLE
SOLID POD and ABOUT: BuildContext issues and Child Instantiation Issues

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#96]
## Description

My showAbout Dialog fails in my InnerPod app after adding the SolidLogin wrapper. 

The code is at https://github.com/gjwgit/innerpod. The main branch is working fine with the about dialog. The dev branch  is failing with a missing build context issue if I choose CONTINUE on the login screen. If I login on the login screen then the about works - the build context is not lost.

The original error I was seeing:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: This BuildContext is no longer valid.
The showDialog function context parameter is a BuildContext that is no longer valid.
This can commonly occur when the showDialog function is called after awaiting a Future. In this situation the BuildContext might refer to a widget that has already been disposed during the await. Consider using a parent context instead.
#0      _debugIsActive (package:flutter/src/material/dialog.dart:1491:5)
#1      showDialog (package:flutter/src/material/dialog.dart:1412:10)
#2      showAboutDialog (package:flutter/src/material/about.dart:190:3)
#3      InnerPod.build.<anonymous closure> (package:innerpod/main.dart:97:17)
<asynchronous suspension>
 ```

I added an async around the function housing the widget so I can gather the appname and version, but I then get the "BuildContext across an async gap" lint warning which I can resolve with checking context.mounted so at least there are no exceptions, but why is the context not available? A consequence is that the info (about) button does not work.

**Comment by gjwgit** [comment]
Seems like if it is inside a Stateful widget it is okay!
